config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#top'

  devise_for :users, controllers: {
    omniauth_callbacks: "omniauth_callbacks"
  }
  devise_scope :users do
    get "/users", to: redirect("/users/sign_up")
  end

  resources :contacts, only: %i[new create] do
    collection do
      post :confirm
      get :complete
    end
  end
end

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer footer-center p-5 bg-base-200 text-base-content rounded">
  <div class="grid grid-flow-col gap-2">
    <%= link_to "Home", "/" %>
    <%= link_to "プライバシーポリシー", "#" %>
    <%= link_to "利用規約", "#" %>
    <%= link_to t(".contact"), new_contact_path %>
  </div>
  <div>
    <p>Copyright © 2023 - All right reserved by HotelChoice</p>
  </div>
</footer>

app/views/shared/_header.html.erb
<header>
  <div class="drawer">
    <input id="my-drawer-3" type="checkbox" class="drawer-toggle" /> 
    <div class="drawer-content flex flex-col">
      <!-- Navbar -->
      <div class="w-full navbar bg-base-300">
        <div class="flex-none lg:hidden">
          <label for="my-drawer-3" aria-label="open sidebar" class="btn btn-square btn-ghost">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" class="inline-block w-6 h-6 stroke-current">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16"></path>
            </svg>
          </label>
        </div>
        <div class="flex-1 px-2 mx-2">
          <h1 class='font-bold text-4xl'>
            <%= link_to 'Hotel Choice', '/' %>
          </h1>
        </div>
        <div class="flex-none hidden lg:block">
          <ul class="menu menu-horizontal">
            <!-- Navbar menu content here -->
            <% if user_signed_in? %>
              <div class="flex-none gap-2">
                <div class="dropdown dropdown-end">
                  <label tabindex="0" class="btn btn-ghost btn-circle avatar">
                    <div class="w-10 rounded-full">
                      <%= image_tag("icon_test.jpg") %>
                    </div>
                  </label>
                  <ul tabindex="0" class="mt-3 z-[1] p-2 shadow menu menu-sm dropdown-content bg-base-100 rounded-box w-52">
                    <li class="border-b border-base-200">
                      <span class="font-bold p-2"><%= current_user.name %></span>
                    </li>
                    <li>
                      <%= link_to "マイページ", "#" %>
                    </li>
                    <li>
                      <%= link_to "新規投稿", "#" %>
                    </li>
                    <li>
                      <%= link_to "診断", "#" %>
                    </li>
                    <li>
                      <%= link_to "リマインド設定", "#" %>
                    </li>
                    <li>
                      <%= link_to 'ログアウト', destroy_user_session_path, data: { turbo_method: :delete } %>
                    </li>
                  </ul>
                </div>
              </div>
            <% else %>
              <li>
                <%= link_to "新規登録", new_user_registration_path %>
              </li>
              <li>
                <%= link_to "ログイン", user_session_path %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
      <!-- Page content here -->
    </div> 
    <div class="drawer-side">
      <label for="my-drawer-3" aria-label="close sidebar" class="drawer-overlay"></label>
      <ul class="menu p-4 min-h-full bg-base-200">
        <!-- Sidebar content here -->
        <% if user_signed_in? %>
          <li class="border-b border-base-200">
            <span class="font-bold p-2"><%= current_user.name %></span>
          </li>
          <li>
            <%= link_to "マイページ", "#" %>
          </li>
          <li>
            <%= link_to "新規投稿", "#" %>
          </li>
          <li>
            <%= link_to "診断", "#" %>
          </li>
          <li>
            <%= link_to "リマインド設定", "#" %>
          </li>
          <li>
            <%= link_to 'ログアウト', destroy_user_session_path, data: { turbo_method: :delete } %>
          </li>
        <% else %>
          <li>
            <%= link_to "新規登録", new_user_registration_path %>
          </li>
          <li>
            <%= link_to "ログイン", user_session_path %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</header>